baseurl: /
languageCode: es-es
title: A Hugo website
theme: "anatole"

googleAnalytics: ''
disqusShortname: ''
ignoreFiles:
  - \.Rmd$
  - \.Rmarkdown$
  - _cache$
  - \.knit\.md$
  - \.utf8\.md$
permalinks:
  post: /:year/:month/:day/:slug/
menu:
  main:
    - name: Sobre Mí
      url: /about/
    - name: Posts
      weight: 200
      identifier: "posts"
      url: "/post/"
    - name: GitHub
      url: https://github.com/marioalbertod
    - name: Twitter
      url: https://twitter.com/marioalbertod_
    - name: ¿Juguemos Go?
      url: https://online-go.com/player/722638/
params:
  MathJaxCDN: //cdnjs.cloudflare.com/ajax/libs
  author: "marioalbertod"
  title: "Mario Alberto"
  profilePicture: "images/avatar.jpg"
  MathJaxVersion: 2.7.5
  description: Sociólogo y jugador de Go
  favicon: favicon.ico
  highlightjsCDN: //cdnjs.cloudflare.com/ajax/libs
  highlightjsLang:
    - r
    - yaml
  highlightjsTheme: github
  highlightjsVersion: 9.12.0
  logo:
    alt: Logo
    height: 50
    url: logo.png 
    width: 50
markup:
  defaultMarkdownHandler: goldmark
  goldmark:
    renderer:
      unsafe: yes
